public class OC_AN_InternalDistributionMembers {
 /*public static List<OC_AN_Group_Member__c>GroupMemberDetails(Id recordID)
{
    List<OC_AN_Group_Member__c>GroupMember=[select id,RecordType.Name, Local_Publisher__c ,User__c, OwnerId, Child_Group__c, 
                                            Contact__c, Account__c, Account__r.Name from  
                                            OC_AN_Group_Member__c where Local_Publisher__c =true AND RecordType.Name='Local Publisher'];
    
     System.debug('GroupMember details>>>'+GroupMember);
    return GroupMember ;
}*/
}