public class OC_TH_CreateCustomMetadataConstants {
public static final string status = 'Not Created';
public static final string labelappend ='Queue_';
public static final string customercompanycode = 'OC_TR_Customer_Company_Code__c';
public static final string legalform = 'OC_TR_LegalForm__c';
public static final string organizationid ='OC_TR_Org_Id__c';
public static final string queuename = 'Queue_Name__c';
public static final String metadataname = 'OC_TR_OrganizationMapping__mdt.';
public static final string packagexml = 'package.xml';
public static final string compare = 'OC_TR_OrganizationMapping__mdt.Queue_';
public static final string created = 'Created';
}